artifacts:
  mymodel:
    path: model.pkl
    desc: My model for s3 folder - should appear in Model Registry
    labels:
    - model
    - s3
    type: model
    meta:
      some: metadata
  data:
    path: data/prepared
    type: data
    desc: Data for the project - should appear in Data Registry

  another-name-3:
    path: another-path-3
    type: model
  another-model-4:
    path: another-path-4
    type: model
  another-model-5:
    path: some-path
    type: model
  model-name-2:
    path: some-model
    type: model
  some-demo-name:
    path: path-to-my-file
    type: model
stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.n_estimators
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features scores.json prc.json
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - scores.json
    plots:
    - prc.json:
        x: recall-ssh
        y: precision-ssh
